// The words the seeded graph is written out of. Six lines of thought, each with
// enough vocabulary that the thousands of notes grown from them read like
// somebody's Zettelkasten rather than like filler.

export interface Topic {
  /** The `domain` label every note in this tree leans toward. */
  domain: string;
  /** The root note's own title — the thought the branch springs from. */
  thesis: string;
  subjects: readonly string[];
  actions: readonly string[];
  objects: readonly string[];
  conditions: readonly string[];
}

export const TOPICS: readonly Topic[] = [
  {
    domain: "cities",
    thesis: "A city remembers what it was told to forget",
    subjects: [
      "a demolished terrace",
      "the ring road",
      "a market that outlived its charter",
      "the tram line nobody rebuilt",
      "a street renamed twice",
      "the flood line painted on a wall",
      "an alley that survives as a right of way",
      "the last industrial chimney",
      "a bus route drawn along an old canal",
      "the gap where a station stood",
      "a park that was once a cemetery",
      "the fence line between two parishes",
      "a bridge wider than its river",
      "the corner shop that keeps its old sign",
    ],
    actions: [
      "outlives",
      "quietly contradicts",
      "sets the price of",
      "keeps the shape of",
      "argues with",
      "is the only evidence for",
      "explains the awkwardness of",
      "survives longer than",
      "constrains",
      "gets mistaken for",
      "is cheaper to keep than",
      "still routes",
    ],
    objects: [
      "the plan that replaced it",
      "everyone who signed it off",
      "the land beneath it",
      "the traffic it was built to carry",
      "the map in the planning office",
      "the neighbourhood's own account of itself",
      "three rounds of consultation",
      "the rent on the street behind it",
      "the walk to school",
      "the boundary it was meant to erase",
      "a century of ownership",
      "the census that missed it",
    ],
    conditions: [
      "the freehold stays undivided",
      "nobody needs the land badly enough",
      "the archive is still legible",
      "the route is cheaper than the alternative",
      "the residents keep saying the old name",
      "no fire clears the block",
    ],
  },
  {
    domain: "biology",
    thesis: "A cell is a decision the body already made",
    subjects: [
      "a slime mould",
      "the gut's second nervous system",
      "a stem cell one division from committing",
      "the mitochondrion's own genome",
      "an immune cell that never met its antigen",
      "a hibernating ground squirrel",
      "the axolotl's blastema",
      "a bacterium sensing its own quorum",
      "the retina's inverted wiring",
      "a fungal network under a hectare of forest",
      "the placenta as a foreign organ",
      "an enzyme that runs backwards",
      "the heart's own pacemaker cells",
      "a virus carrying somebody else's gene",
    ],
    actions: [
      "solves",
      "computes without",
      "pays for",
      "refuses",
      "keeps a record of",
      "trades precision for",
      "is faster than",
      "wastes",
      "commits to",
      "cannot undo",
      "outsources",
      "gambles on",
    ],
    objects: [
      "a maze with no map",
      "a signal it will never receive again",
      "the cost of being wrong",
      "the whole organism's budget",
      "a decision made three divisions ago",
      "the temperature it will meet tomorrow",
      "an evolutionary bet from the Cambrian",
      "half the energy it takes in",
      "its own ability to divide again",
      "the boundary between self and not-self",
      "a repair it can only make once",
      "the timing of everything downstream",
    ],
    conditions: [
      "the gradient holds",
      "the energy budget is not already spent",
      "nothing else is competing for the same receptor",
      "the tissue stays below its oxygen floor",
      "the signal arrives before the window closes",
      "the population stays above quorum",
    ],
  },
  {
    domain: "computation",
    thesis: "Every index is a bet about the question you will ask",
    subjects: [
      "a B-tree with a wrong leading column",
      "the query planner's cost model",
      "an append-only log",
      "a cache with no eviction story",
      "the retry that made the outage worse",
      "a schema migration nobody could reverse",
      "the id generated on the client",
      "a fractional index",
      "an eventually consistent read",
      "the timeout that hides a deadlock",
      "a checksum nobody verifies",
      "the sort that fits in memory today",
      "a foreign key across two services",
      "the feature flag left on for a year",
    ],
    actions: [
      "encodes",
      "amortises",
      "hides",
      "makes cheap",
      "makes impossible",
      "is a bet on",
      "postpones",
      "quietly costs",
      "linearises",
      "trades away",
      "cannot survive",
      "is only correct while",
    ],
    objects: [
      "a question the product has not asked yet",
      "the write path",
      "one failure mode by creating two",
      "the cost of being wrong at 3am",
      "every read that comes after it",
      "a decision made before the data existed",
      "the difference between p50 and p99",
      "somebody else's on-call week",
      "the ordering two peers must agree on",
      "a migration that would take the table offline",
      "the memory the process does not have",
      "correctness under concurrency",
    ],
    conditions: [
      "the working set fits in memory",
      "clocks stay within a few milliseconds",
      "the write rate stays under the compaction rate",
      "no client retries blindly",
      "the cardinality estimate is roughly right",
      "the second column is never queried alone",
    ],
  },
  {
    domain: "language",
    thesis: "Grammar is the fossil record of what mattered",
    subjects: [
      "an irregular verb",
      "the evidential mood",
      "a case ending that survived its case system",
      "the definite article in a language without one",
      "a word borrowed twice by different routes",
      "the second person plural",
      "an untranslatable particle",
      "a euphemism that outlived its taboo",
      "the sound change that split a dialect",
      "a name for a colour nobody separates",
      "the passive nobody uses in speech",
      "a proverb quoted with its meaning reversed",
      "the spelling frozen by a printing press",
      "a pronoun that became a slur and back",
    ],
    actions: [
      "preserves",
      "marks",
      "erases",
      "is the last trace of",
      "makes obligatory",
      "makes unsayable",
      "distinguishes",
      "collapses",
      "is defended by",
      "outlives",
      "conceals",
      "reveals",
    ],
    objects: [
      "a distinction the speakers stopped caring about",
      "who is responsible for the claim",
      "a hierarchy nobody would state out loud",
      "the difference between seeing and hearing it",
      "an economy that no longer exists",
      "the border between two armies",
      "a religious calendar",
      "kinship the census does not record",
      "what counts as polite at a distance",
      "the century the word was borrowed in",
      "who is allowed to be vague",
      "the shape of a room people spoke in",
    ],
    conditions: [
      "children keep hearing it before they are five",
      "the written form stays prestigious",
      "the community stays dense enough",
      "no reform standardises it away",
      "the distinction still earns its keep",
      "the borrowing language has the sound",
    ],
  },
  {
    domain: "economics",
    thesis: "Money is a promise with a stranger's face on it",
    subjects: [
      "a tally stick",
      "the clearing house nobody sees",
      "a currency peg defended past its cost",
      "an insurance market with no reinsurer",
      "the price of bread under a subsidy",
      "a debt written off in silence",
      "the informal credit of a village shop",
      "a bond nobody intends to hold to maturity",
      "the exchange rate at the border market",
      "a savings club rotating weekly",
      "the wage that clears no market",
      "a tax collected in kind",
      "the deposit insurance limit",
      "an invoice used as currency",
    ],
    actions: [
      "settles",
      "defers",
      "prices",
      "socialises",
      "makes liquid",
      "hides the cost of",
      "is a claim on",
      "depends on nobody testing",
      "substitutes for",
      "collapses into",
      "is enforced by",
      "outlasts",
    ],
    objects: [
      "a promise nobody wrote down",
      "trust between people who will never meet",
      "the risk the seller cannot carry",
      "next year's harvest",
      "a state's willingness to be believed",
      "the difference between a shortage and a queue",
      "an obligation older than the currency",
      "the balance sheet it never appears on",
      "everyone who is not in the room",
      "the moment everyone asks at once",
      "a legal system in another country",
      "the government that issued it",
    ],
    conditions: [
      "nobody redeems all of it at once",
      "the counterparty stays solvent",
      "the state keeps taxing in this unit",
      "the shop still extends credit",
      "the queue is shorter than the shortage",
      "the peg is cheaper to hold than to drop",
    ],
  },
  {
    domain: "music",
    thesis: "A rhythm is an argument you can dance to",
    subjects: [
      "a clave pattern",
      "the swung eighth",
      "a drum machine's factory preset",
      "the silence before the downbeat",
      "a bar of five in a dance record",
      "the sampled break nobody credited",
      "an instrument tuned to a room",
      "the singer breathing in time",
      "a modal scale with no leading tone",
      "the click track's tyranny",
      "a chord borrowed from the parallel minor",
      "the fade-out as an ending",
      "a bassline that refuses the root",
      "the hi-hat carrying the whole groove",
    ],
    actions: [
      "argues for",
      "makes room for",
      "refuses to resolve",
      "predicts",
      "delays",
      "borrows",
      "survives",
      "reorganises",
      "makes audible",
      "cannot be notated as",
      "teaches the body",
      "is the whole reason for",
    ],
    objects: [
      "where the dancers put their weight",
      "a resolution the listener supplies",
      "two bars of anticipation",
      "the room it was recorded in",
      "an entire genre built on four seconds",
      "the difference between playing and performing",
      "a tuning system somebody had to lose",
      "the singer's next breath",
      "what the ear expects and does not get",
      "the tempo everyone remembers wrongly",
      "a tradition it was stolen from",
      "the silence it is measured against",
    ],
    conditions: [
      "the tempo stays where the body can find it",
      "the room is not too live",
      "the players are listening to each other",
      "nobody quantises it flat",
      "the dancers already know the pattern",
      "the recording keeps the mistake",
    ],
  },
];

/** Titles for a note that opens a line of enquiry. */
export const OPENING_TEMPLATES: readonly string[] = [
  "{Subject} {action} {object}",
  "Why {subject} {action} {object}",
  "The case that {subject} {action} {object}",
  "Nobody planned it: {subject} {action} {object}",
  "On {subject}, and what it {action}",
];

/** Titles for a note that springs from the one above it. */
export const FOLLOWING_TEMPLATES: readonly string[] = [
  "But only while {condition}",
  "This holds until {condition}",
  "A counter-case: {subject}",
  "What it costs: {subject} {action} {object}",
  "Restated: {subject} {action} {object}",
  "Where this breaks — {subject}",
  "The same argument about {subject}",
  "If that is true, {subject} {action} {object}",
  "Against the last note: {subject} still {action} {object}",
  "A smaller version: {subject}",
  "Ask instead whether {subject} {action} {object}",
  "The evidence is thin unless {condition}",
];

export const PARAGRAPH_TEMPLATES: readonly string[] = [
  "{Subject} {action} {object}. That is easy to say and hard to hold, because the moment {condition} stops being true the whole claim has to be made again from the start.",
  "Start with the ordinary case. {Subject} {action} {object}, and nobody involved would describe it that way. The description is ours, imposed afterwards, which is exactly why it is worth writing down.",
  "The interesting part is not that {subject} {action} {object}. It is that this keeps working while {condition}, and that nobody checks whether it still does.",
  "Consider what has to be true first: {condition}. Given that, {subject} {action} {object} without anyone deciding it should.",
  "There is a cheaper explanation. {Subject} {action} {object} because that was the path of least resistance, not because it was chosen, and the difference matters when somebody proposes changing it.",
  "Held against the neighbouring note this looks like a contradiction. It is not. {Subject} {action} {object} at one scale and does the opposite at another, and the scale is doing the work.",
];

export const LIST_TEMPLATES: readonly string[] = [
  "{subject} — {action} {object}",
  "{condition}, and then everything else follows",
  "{Subject}: the case nobody argues about",
  "what breaks first if {condition} stops being true",
];

export const QUESTION_TEMPLATES: readonly string[] = [
  "Does {subject} {action} {object} anywhere else?",
  "What would falsify this?",
  "Who benefits while {condition}?",
  "Is {subject} the cause or the residue?",
];
