// Regenerates `src/lib/emoji/unicode.ts` from the Unicode set.
//
// `unicode-emoji-json` carries the emoji and their groups; `emojilib` carries
// the search words. Neither ships the other, and the picker needs both — a
// shortcode to resolve `:code:` against, and words to find it by.
//
//   pnpm --filter @sloppy/ui emoji

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import prettier from 'prettier';
import groups from 'unicode-emoji-json/data-by-group.json' with { type: 'json' };
import keywordsByChar from 'emojilib' with { type: 'json' };

const out = fileURLToPath(new URL('../src/lib/emoji/unicode.ts', import.meta.url));

/** A shortcode is what stored text names, so two emoji may never share one. */
const taken = new Set();
let clashes = 0;

const categories = groups.map((group) => ({
	name: group.name,
	emoji: group.emojis.flatMap((entry) => {
		if (taken.has(entry.slug)) {
			clashes += 1;
			return [];
		}
		taken.add(entry.slug);
		// emojilib leads with its own name for the emoji; the rest are aliases.
		const words = (keywordsByChar[entry.emoji] ?? []).slice(1);
		return [{ shortcode: entry.slug, char: entry.emoji, keywords: words }];
	})
}));

const body = categories
	.map(
		(category) =>
			`\t{\n\t\tname: ${JSON.stringify(category.name)},\n\t\temoji: [\n` +
			category.emoji
				.map((one) => {
					const words = one.keywords.length ? `, keywords: ${JSON.stringify(one.keywords)}` : '';
					return `\t\t\t{ shortcode: ${JSON.stringify(one.shortcode)}, char: ${JSON.stringify(one.char)}${words} }`;
				})
				.join(',\n') +
			'\n\t\t]\n\t}'
	)
	.join(',\n');

const source = `// GENERATED by scripts/emoji.mjs — do not edit. Run \`pnpm --filter @sloppy/ui emoji\`.
//
// The whole Unicode emoji set, grouped the way the picker shows it.
// \`shortcode\` is what \`:code:\` and \`::code::\` resolve against; \`keywords\`
// are search-only aliases and never appear in stored text.

export interface UnicodeEmoji {
	shortcode: string;
	char: string;
	keywords?: readonly string[];
}

export interface UnicodeEmojiCategory {
	name: string;
	emoji: readonly UnicodeEmoji[];
}

export const UNICODE_EMOJI: readonly UnicodeEmojiCategory[] = [
${body}
];
`;

// Formatted here, or the next run leaves a file `format:check` fails on and the
// person who regenerated it inherits a red build they did not cause.
writeFileSync(
	out,
	await prettier.format(source, {
		...(await prettier.resolveConfig(out)),
		filepath: out
	})
);

const total = categories.reduce((sum, one) => sum + one.emoji.length, 0);
console.log(
	`${total} emoji across ${categories.length} groups (${clashes} duplicate slugs dropped)`
);
